src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;



#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'Cette adresse email est déjà utilisée par un autre compte')]
#[UniqueEntity(fields: ['pseudonym'], message: 'Ce pseudonyme est déjà utilisé par un autre compte')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 50, unique: true)]
    private $pseudonym;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $birthDate;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'string', nullable: true)]
    private $password;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $pictureProfil;

    #[ORM\Column(type: 'text', nullable: true)]
    private $Biography;

    #[ORM\Column(type: 'datetime')]
    private $registrationDate;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Recipe::class, orphanRemoval: true)]
    private $recipes;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private $comments;

    #[ORM\Column(type: 'string', length: 21, nullable: true, options: ['fixed' => true])]
    private $googleId;


    public function __construct()
    {
        $this->setRegistrationDate(new \DateTime());
        $this->recipes = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudonym(): ?string
    {
        return $this->pseudonym;
    }

    public function setPseudonym(string $pseudonym): self
    {
        $this->pseudonym = $pseudonym;

        return $this;
    }

    public function getBirthDate(): ?\DateTime
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTime $birthDate = null): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPictureProfil(): ?string
    {
        return $this->pictureProfil;
    }

    public function setPictureProfil(?string $pictureProfil): self
    {
        $this->pictureProfil = $pictureProfil;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->Biography;
    }

    public function setBiography(?string $Biography): self
    {
        $this->Biography = $Biography;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registrationDate;
    }

    public function setRegistrationDate(\DateTimeInterface $registrationDate): self
    {
        $this->registrationDate = $registrationDate;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);

    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipe $recipe): self
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes[] = $recipe;
            $recipe->setAuthor($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): self
    {
        if ($this->recipes->removeElement($recipe)) {
            // set the owning side to null (unless already changed)
            if ($recipe->getAuthor() === $this) {
                $recipe->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\EditPasswordTypeFormType;
use App\Form\EditProfilFormType;
use App\Form\EditProfilPhotoTypeFormType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;



#[Route('', name: 'main_')]
class MainController extends AbstractController
{
    /**
     * contrôleur de la page d'accueil
     */
    #[Route('/', name: 'home')]
    public function home(): Response
    {

        return $this->render('main/home.html.twig');
    }



    /**
     * Controller to profil page
     */
    #[Route('/mon-profil/', name: 'profils')]
    #[IsGranted("ROLE_USER")]
    public function profils(): Response
    {
        return $this->render('main/profils.html.twig');
    }



    /**
     * Controller to profil parameter
     */
    #[Route('/mon-profil/options/', name: 'profils_parameter')]
    #[IsGranted("ROLE_USER")]
    public function profilsParameter(Request $request, EntityManagerInterface $entityManager, ): Response
    {

        // Caught connect user
        $user = $this->getUser();

        // Create a new form
        $profilForm = $this->createForm(EditProfilFormType::class, $user);

        // Filling form with POST data
        $profilForm->handleRequest($request);

        if($profilForm->isSubmitted() && $profilForm->isValid()){

            $user = $profilForm->getData();

            $entityManager->persist($user);
            $entityManager->flush();

            // Success message
            $this->addFlash("success", "Profil modifié avec succès !");

            // Redirection to profil page
            return $this->redirectToRoute("main_profils");

        }

        return $this->render('main/profils_parametre.html.twig', [
            'profilForm' => $profilForm->createView()
        ]);

    }

    /**
     * Controller to edit password parameter
     */
    #[Route('/mon-profil/options/modifier-mot-de-passe/', name: 'profils_parameter_edit_password')]
    #[IsGranted("ROLE_USER")]
    public function profilEditPassword(UserPasswordHasherInterface $hasher, ManagerRegistry $doctrine, Request $request): Response
    {


        $connectedUser = $this->getUser();

        $editPasswordForm = $this->createForm(EditPasswordTypeFormType::class, $connectedUser);

        $editPasswordForm->handleRequest($request);

        if($editPasswordForm->isSubmitted() && $editPasswordForm->isValid()){

            $newPassword = $editPasswordForm->get('plainPassword')->getData();

            dump($newPassword);

            $hashOfNewPassword = $hasher->hashPassword($connectedUser, $newPassword);

            $connectedUser->setPassword($hashOfNewPassword);

            try {
                $em = $doctrine->getManager();
                $em->flush();

                $this->addFlash('success', 'Mot de passe modifié avec succès !');
            } catch (\Exception $exception){


                $this->addFlash('error', "Désolé, un problème est survenue !");

            }

           return $this->redirectToRoute("main_profils_parameter");

        }

        return $this->render('main/profils_parametre_edit_password.html.twig', [
            "editPasswordForm" => $editPasswordForm->createView(),
        ]);

    }

    /**
     * Controller to edit profil picture
     */
    #[Route('/mon-profil/options/modifier-photo-de-profil/', name: 'profils_parameter_edit_picture')]
    #[IsGranted("ROLE_USER")]
    public function profilEditPicture(Request $request, ManagerRegistry $doctrine, EntityManagerInterface $entityManager): Response
    {


        $connectedUser = $this->getUser();

        $editPictureForm = $this->createForm(EditProfilPhotoTypeFormType::class);

        $editPictureForm->handleRequest($request);

        if($editPictureForm->isSubmitted() && $editPictureForm->isValid()){

            $newPicture = $editPictureForm->get("pictureProfil")->getData();

            if($connectedUser->getPictureProfil() != null &&
            file_exists($this->getParameter('app.user.photo.directory') . $this->getUser()->getPictureProfil())
            ){
                unlink( $this->getParameter('app.user.photo.directory') . $connectedUser->getPictureProfil() );
            }

            do{
                $newFileName = md5(time() . rand() .  uniqid() ) . '.' . $newPicture->guessExtension();
            }while(file_exists($this->getParameter('app.user.photo.directory') . $newFileName));

            $connectedUser->setPictureProfil($newFileName);

            try{
                $em = $doctrine->getManager();
                $em->flush();

                $newPicture->move(
                    $this->getParameter('app.user.photo.directory'),
                    $newFileName
                );

                $this->addFlash('success',"Photo modifiée avec succès !");
            }catch (\Exception $exception){
                $this->addFlash('success',"Désolé, un problème est survenue !");
            }

        }

        return $this->render('main/profils_parametre_edit_picture.html.twig', [
            "editPictureForm"=>$editPictureForm->createView()
        ]);

    }



    /**
     * Controller to profil personal recipe
     */
    #[Route('/mon-profil/mes-recettes/', name: 'profils_personal_recipe')]
    #[IsGranted("ROLE_USER")]
    public function profilsPersonalRecipe(ManagerRegistry $doctrine, Request $request, PaginatorInterface $paginator): Response
    {

        $requestedPage = $request->query->getInt('page', 1);

        if($requestedPage < 1){
            throw new NotFoundHttpException();
        }

        $em = $doctrine->getManager();

        $query = $em->createQuery('SELECT a FROM App\Entity\Recipe a ORDER BY a.publicationDate DESC');

        $recipes = $paginator->paginate(
            $query,
            $requestedPage,
            9,
        );

        return $this->render('main/profils_personal_recipe.html.twig', [
            "recipes" => $recipes,
        ]);
    }


    /**
     * Controller to profil favorite recipe
     */
    #[Route('/mon-profil/mes-recettes-favorites/', name: 'profils_favorite_recipe')]
    #[IsGranted("ROLE_USER")]
    public function profilsFavoriteRecipe(): Response
    {
        return $this->render('main/profils_favorite_recipe.html.twig');
    }


    /**
     * Controller to delete profil
     */
    #[Route('/mon-profil/supprimer-mon-compte/', name: 'profils_delete')]
    #[IsGranted("ROLE_USER")]
    public function profilsDelete(Request $request, UserRepository $userRepository, ManagerRegistry $doctrine): Response
    {
        $user = $this->getUser();

        if($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token')) ||
            $this->isCsrfTokenValid('delete'.$user->getGoogleId(), $request->request->get('_token'))
        ){

            $this->container->get('security.csrf.token_storage')->setToken(null);
            $userRepository->remove($user->getId(), true);

        }

        $session = new Session();
        $session->invalidate();

        try{
            $em = $doctrine->getManager();

            $em->getRepository(User::class)->findOneById($user->getId());

            $em->remove($user);

            $em->flush();

            $this->addFlash('success', "Votre compte à été supprimé avec succès !");

        }catch (\Exception $exception){

            $this->addFlash('error', "Désolé, un problème est survenue !");

        }

        return $this->redirectToRoute('main_home');
    }



    /*
     * contrôleur de la page catégories
     */
    #[Route('/categories/', name: 'categories')]
    public function categories(): Response
    {

        return $this->render('main/categories.html.twig');
    }



    /**
     * contrôleur de la page contact
     */
    #[Route('/contact/', name: 'contact')]
    public function contact(): Response
    {

        return $this->render('main/contact.html.twig');
    }



    /**
     * contrôleur de la page credit images
     */
    #[Route('/credit-images/', name: 'credit-images')]
    public function credit(): Response
    {

        return $this->render('main/credit-images.html.twig');
    }


}

templates/main/categories.html.twig
{% extends 'base.html.twig' %}
{% block title %}Catégories{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row w-100 d-flex justify-content-center">

            <div class=" col-10 my-3 col-md-5  my-md-5 text-center">
                <div class="py-1 catégories-zoom-style">

                    <a href="/recettes/categories/1/" class="category-style-h3" >

                            <img class="img-fluid" src="{{ asset('images/cat_chaudron.png') }}" alt="chaudron">
                            <h3 class="text-center my-3">Entrée</h3>
                    </a>
                </div>
            </div>

            <div class="col-10 my-3 col-md-5 my-md-5 text-center">
                <div class="py-1 catégories-zoom-style">

                    <a href="/recettes/categories/2/" class="category-style-h3" >

                            <img class="img-fluid" src="{{ asset('images/cat_plat.png') }}" alt="chaudron">
                            <h3 class="text-center my-3">Plat</h3>
                    </a>
                </div>
            </div>

            <div class="col-10 my-3 col-md-5  my-md-5 text-center">
                <div class="py-1 catégories-zoom-style">

                    <a href="/recettes/categories/3/" class="category-style-h3" >

                        <img class="img-fluid" src="{{ asset('images/cat_donut.png') }}" alt="chaudron">
                        <h3 class="text-center my-3 ">Dessert</h3>
                    </a>
                </div>
            </div>

            <div class="col-10 my-3 col-md-5  my-md-5 text-center">
                <div class="py-1 catégories-zoom-style">

                    <a href="/recettes/categories/4/" class="category-style-h3" >

                        <img class="img-fluid" src="{{ asset('images/cat_cocktail.png') }}" alt="chaudron">
                        <h3 class="text-center my-3 ">Cocktail</h3>
                    </a>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/main/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}

    <div class="container-fluid" >

        <h1 class="col-12 text-center py-5">Coming Soon...</h1>

        <div class="text-center">
            <img class="img-fluid col-10 col-md-8 col-lg-4 border border-light rounded" src="{{ asset('images/pexels-photo-211122.jpeg') }}" alt="">
        </div>

    </div>

{% endblock %}

templates/main/credit-images.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crédit images{% endblock %}

{% block body %}
    <div class="container-fluid">

        <div class="row text-center mx-auto mt-5">

            <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                <div class="card bg-dark my-3 mx-auto p-0" style="width: 18rem;">
                    <img src="{{ asset('images/bibimbap.png') }}" class="card-img-top" alt="logo_ramen">
                    <div class="card-body">
                        <a class="text-light" href="https://www.flaticon.com/fr/icone-premium/bibimbap_2276931?term=bibimbap&page=1&position=1&page=1&position=1&related_id=2276931&origin=search" target="_blank" title="nourriture icônes">Nourriture icônes créées par justicon - Flaticon</a>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                <div class="card bg-dark my-3 mx-auto p-0" style="width: 18rem;">
                    <img src="{{ asset('images/logo_potions.png') }}" class="card-img-top" alt="logo_potions">
                    <div class="card-body">
                        <a class="text-light" href="https://www.flaticon.com/free-icon/potion_1205587?term=potion%20flask&page=1&position=2&page=1&position=2&related_id=1205587&origin=search" target="_blank"  title="potion icons">Potion icons created by Freepik - Flaticon</a>
                    </div>
                </div>
            </div>


            <div class="col-12 col-md-6 col-lg-4 p-0 col-xl-3">
                <div class="card bg-dark my-3 mx-auto p-0" style="width: 18rem;">
                    <img src="{{ asset('images/logo_chaudron.png') }}" class="card-img-top" alt="logo_chaudron">
                    <div class="card-body">
                        <a class="text-light" href="https://www.flaticon.com/fr/icone-gratuite/pot_5438603?related_id=5438603" target="_blank"  title="potion icônes">Chaudron icônes créées par Vitaly Gorbachev - Flaticon</a>
                    </div>
                </div>
            </div>


            <div class="col-12 col-md-6 col-lg-4 p-0 col-xl-3">
                <div class="card bg-dark my-3 mx-auto p-0" style="width: 18rem;">
                    <img src="{{ asset('images/logo_donut.png') }}" class="card-img-top" alt="logo_donut">
                    <div class="card-body">
                        <a class="text-light" href="https://www.flaticon.com/fr/icone-gratuite/donut_214681?term=donut&page=1&position=3&page=1&position=3&related_id=214681&origin=search" target="_blank"  title="donut icônes">Donut icônes créées par Pixel Buddha - Flaticon</a>
                    </div>
                </div>
            </div>


            <div class="col-12 col-md-6 col-lg-4 p-0 col-xl-3">
                <div class="card bg-dark text-light my-3 mx-auto" style="width: 18rem;">
                    <img src="{{ asset('images/pexels-photo-211122.jpeg') }}" class="card-img-top" alt="Coming soon">
                    <div class="card-body">
                        <a class="text-light" href="https://www.pexels.com/fr-fr/photo/sous-signalisation-de-construction-sur-clavier-d-ordinateur-portable-211122/" target="_blank"  title="donut icônes">Under Construction par Fernando Arcos - Pexels</a>
                    </div>
                </div>
            </div>


        </div>

    </div>


{% endblock %}

templates/main/home.html.twig
{% extends 'base.html.twig' %}

{% block title%}Accueil{% endblock %}

{% block body %}

    <!-- PAGE -->

    <div class="container-fluid">

        <div class="row container-page">

            <!-- presentation text -->
            <div class=" text-center mx-auto py-5 px-5 text-container col-sm-8 col-lg-4">
                <h1 class="mx-auto">Geek In Taste</h1>
                <h2 class="mx-auto">Bienvenue dans l'aventure de la cuisine dans la pop culture</h2>
            </div>

            <!-- Main picture -->
            <div class=" d-none d-sm-block col-md-9 col-lg-4 text-center mx-auto main-picture">
                <img class=" text-center mx-auto " src="{{ asset('images/bibimbap.png') }}" alt="ramen">
            </div>

            <!-- Small icons section  -->
            <div class="small-icons-container col-lg-4">
                <div class="small-icons">
                    <div class="icons-text-container text-center">
                        <img src="{{ asset('images/logo_potions.png') }}" alt="logo_potion">
                        <h3>Potions</h3>
                    </div>
                    <div class="icons-text-container text-center">
                        <img src="{{ asset('images/logo_chaudron.png') }}" alt="logo_chaudron">
                        <h3>Mixtures</h3>
                    </div>
                    <div class="icons-text-container text-center">
                        <img src="{{ asset('images/logo_donut.png') }}" alt="logo_donut">
                        <h3 class="mb-5">Douceurs</h3>
                    </div>
                </div>
            </div>

        </div>






{% endblock %}

templates/main/profils.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profil{% endblock %}

{% block body %}

    <div class="container-fluid">

        {# Profil header #}
        <header class="row my-4">

            {# Pseudonym #}
            <section
                    class="
                    col-12
                    col-xl-6 my-xl-auto"
            >
                <h1 class="profil-name text-center pb-3 pb-md-4">{{ app.user.pseudonym }}</h1>
            </section>

            {# Photo #}
            <div class="profil-user-picture col-6 offset-3 pb-3 pb-md-4 col-lg-4 offset-lg-4 col-xl-4 offset-xl-2 mx-auto d-flex flex-column align-items-center">

                {% if app.user.pictureProfil is null %}

                    <img src="{{ asset('images/profil-default.jpg') }}" alt="" class="img-fluid img-thumbnail">

                {% else %}

                    <img src="{{ asset('images/profils/' ~ app.user.pictureProfil) }}" alt="" class="img-fluid img-thumbnail">

                {% endif %}

                <a href="{{ path('main_profils_parameter_edit_picture') }}" class="text-center text-decoration-none picture-text-style pt-2">Modifier votre photo de profil</a>

            </div>

        </header>

        {# Personal information #}
        <section class="row my-4">

            <div class="user-info-profil col-10 offset-1 mb-3 col-md-8 offset-md-2 mb-md-5">

                <p><span class="text-danger fw-bold text-decoration-underline">Mon pseudonyme :</span> {{ app.user.pseudonym }}</p>

                <p><span class="text-danger fw-bold text-decoration-underline">Mon adresse email :</span> {{ app.user.email }}</p>

                <p><span class="text-danger fw-bold text-decoration-underline">Ma date de naissance :</span> {{ app.user.birthDate|date("d/m/Y") }}</p>

                <p><span class="text-danger fw-bold text-decoration-underline">Ma biographie :</span> {{ app.user.biography }}</p>

            </div>

        </section>

        {# Account parameter #}
        <nav class="row my-4 profil-link">

            <div class="col-12 pb-3 col-md-10 offset-md-1 pb-md-4">

                <p>Pour mettre à jour vos informations personnelles afin de sécuriser votre compte : </p>

                <a href="{{ path('main_profils_parameter') }}" class="offset-1"><i class="fa-solid fa-user-gear"></i>Mes informations personnelles</a>

            </div>

        </nav>

        {# My recipe #}
        <nav class="row mt-4 profil-link">

            <div class="col-12 pb-3 col-md-10 offset-md-1 pb-md-4">

                <p>Pour visualiser et enrichir votre grimoire de recettes : </p>

                <div class="d-flex flex-column">
                    <a href="{{ path('main_profils_personal_recipe') }}" class="offset-1"><i class="fa-solid fa-book-bookmark"></i>Mes recettes</a>

                    <a href="{{ path('app_recipe') }}" class="offset-1"><i class="fa-solid fa-book-medical"></i>Créer une recette</a>

                    <a href="{{ path('main_contact') }}" class="offset-1"><i class="fa-solid fa-heart-circle-check"></i>Mes recettes préférées</a>
                </div>

            </div>

        </nav>

        {# Account statement #}
        <nav class="row profil-link">

            <div class="col-12 col-md-10 offset-md-1">

                <p>Pour gérer l'état de votre compte :</p>

                <div class="d-flex flex-column">
                    {# Disconnection #}
                    <a href="{{ path('app_logout') }}" class="offset-1"><i class="fa-solid fa-right-from-bracket"></i>Déconnexion</a>

                    {# Delete account #}

                    <a href="{{ path('main_profils_delete') }}" class="offset-1"><i class="fa-solid fa-folder-minus"></i>Supprimer mon compte</a>
                </div>

            </div>

        </nav>


    </div>

{% endblock %}

templates/main/profils_delete.html.twig
{% extends 'base.html.twig' %}
{% block title %}Suppression du compte{% endblock %}

{% block body %}

{% endblock %}

templates/main/profils_favorite_recipe.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mes recettes favorites{% endblock %}


{% block body %}

    {# Menu principal #}
    {% include '_partials/_main_profil_slidebar.html.twig' %}

    <div class="container-fluid">
        <div class="row">
            <div id="main">
                <!-- Add all your websites page content here  -->
            </div>
        </div>
    </div>


{% endblock %}

templates/main/profils_parametre.html.twig
{% extends 'base.html.twig' %}
{% block title %}Options du compte{% endblock %}


{% block body %}

    {# Menu #}
    {% include '_partials/_main_profil_slidebar.html.twig' %}

    <div class="container-fluid">

        <div class="row">

            <div id="main">

                <div class="row">
                    <h1 class="col-12 text-center my-5 text-danger">Modifier vos informations personnelles</h1>
                </div>

                {# Link to change password  #}
                <div class="row">
                    <nav class="col-11 offset-1 d-flex flex-column align-items-center pb-5 col-lg-11 offset-lg-1 profil-link-parameter">

                        <a href="{{ path('main_profils_parameter_edit_password') }}" class="d-flex align-items-center">
                            <i class="mb-3 me-2 fa-solid fa-key"></i>
                            <h3>Modifier votre mot de passe</h3>
                        </a>

                        <a href="{{ path('main_profils_parameter_edit_picture') }}" class="d-flex align-items-center">
                            <i class="mb-3 me-2 fa-solid fa-camera-retro"></i>
                            <h3>Modifier votre photo de profil</h3>
                        </a>

                    </nav>

                </div>

                {# Edit profil form #}
                <div class="row">

                    {{ form_start( profilForm ) }}
                    {{ form_errors( profilForm ) }}

                    <div class="col-10 offset-1 py-3 col-lg-11 offset-lg-1 profil-parameter-separator d-lg-flex">

                        <h3 class="col-lg-5">Votre pseudonyme</h3>

                        <div class="col-lg-7">{{ form_row( profilForm.pseudonym ) }}</div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-10 offset-1 py-3 col-lg-11 offset-lg-1 profil-parameter-separator d-lg-flex">

                        <h3 class="col-lg-5">Votre email</h3>

                        <div class="col-lg-7">{{ form_row( profilForm.email ) }}</div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-10 offset-1 py-3 col-lg-11 offset-lg-1 profil-parameter-separator d-lg-flex">

                        <h3 class="col-lg-5">Votre date de naissance</h3>

                        <div class="col-lg-7">{{ form_row( profilForm.birthDate ) }}</div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-10 offset-1 py-3 col-lg-11 offset-lg-1 d-lg-flex">

                        <h3 class="col-lg-5">Votre biographie</h3>

                        <div class="col-lg-7">{{ form_row( profilForm.biography ) }}</div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-10 offset-1 py-3">

                        <div>{{ form_row( profilForm.save ) }}</div>
                        {{ form_end( profilForm ) }}

                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}

templates/main/profils_parametre_edit_password.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modifier mot de passe{% endblock %}


{% block body %}

    {# Menu #}
    {% include '_partials/_main_profil_slidebar.html.twig' %}

    <div class="container-fluid">

        <div class="row">

            <div id="main">
                <div class="row">
                    <h1 class="col-12 text-center my-5 text-danger"> Modifier votre mot de passe</h1>
                </div>

                <div class="row">
                    <div class="col-10 offset-1 py-3 col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">

                        {# TODO: voir pour péter les 2 champ #}
                        {{ form_start( editPasswordForm ) }}
                        {{ form_errors( editPasswordForm ) }}
                        <div id="passField">
                            {{ form_row( editPasswordForm.plainPassword ) }}
                            <p id="bubble">Votre mot de passe doit contenir obligatoirement une minuscule, une majuscule, un chiffre et un caractère spécial et un minimum de 8 caractères</p>
                        </div>

                    </div>
                </div>
                
                <div class="row">
                    <div class="col-10 offset-1 py-3 col-xl-8 offset-xl-2">

                        <div>{{ form_row( editPasswordForm.save ) }}</div>
                        {{ form_end( editPasswordForm ) }}

                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}